# Dotfiles tools
brew "chezmoi"
brew "antidote"
brew "zellij"
brew "eza"
brew "zoxide"
brew "atuin"
brew "starship"
brew "vivid"

# Core CLI
brew "git"
brew "gh"
brew "wget"
brew "fzf"
brew "fd"
brew "ripgrep"
brew "lazygit"
brew "tree-sitter-cli"
brew "1password-cli"
brew "mas"

# Editor deps (LazyVim)
brew "neovim"
brew "luarocks"
brew "imagemagick"
brew "ghostscript"
brew "tectonic"

# Dev tools
brew "mise"
brew "pnpm"
brew "go"
brew "rustup"
brew "dotnet"

# macOS apps
cask "hammerspoon"
cask "linearmouse"
cask "nikitabobko/tap/aerospace"
cask "vivaldi"
cask "tidal"
cask "postman"
cask "proton-mail"
cask "protonvpn"
cask "proton-drive"
cask "jetbrains-toolbox"
cask "setapp"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "little-snitch"
cask "notion"
cask "obsidian"
cask "figma"
cask "linear-linear"
cask "docker"
cask "shapr3d"
cask "ghostty"
cask "font-hack-nerd-font"
cask "font-0xproto-nerd-font"
